/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __ADVERTISE_GENERATED_H__
#define __ADVERTISE_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.bluez.LEAdvertisingManager1 */

#define TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1 (org_bluez_leadvertising_manager1_get_type ())
#define ORG_BLUEZ_LEADVERTISING_MANAGER1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1, OrgBluezLEAdvertisingManager1))
#define IS_ORG_BLUEZ_LEADVERTISING_MANAGER1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1))
#define ORG_BLUEZ_LEADVERTISING_MANAGER1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1, OrgBluezLEAdvertisingManager1Iface))

struct _OrgBluezLEAdvertisingManager1;
typedef struct _OrgBluezLEAdvertisingManager1 OrgBluezLEAdvertisingManager1;
typedef struct _OrgBluezLEAdvertisingManager1Iface OrgBluezLEAdvertisingManager1Iface;

struct _OrgBluezLEAdvertisingManager1Iface
{
  GTypeInterface parent_iface;

  gboolean (*handle_register_advertisement) (
    OrgBluezLEAdvertisingManager1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_advertisement,
    GVariant *arg_options);

  gboolean (*handle_unregister_advertisement) (
    OrgBluezLEAdvertisingManager1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_object_path);

};

GType org_bluez_leadvertising_manager1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_bluez_leadvertising_manager1_interface_info (void);
guint org_bluez_leadvertising_manager1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_bluez_leadvertising_manager1_complete_register_advertisement (
    OrgBluezLEAdvertisingManager1 *object,
    GDBusMethodInvocation *invocation);

void org_bluez_leadvertising_manager1_complete_unregister_advertisement (
    OrgBluezLEAdvertisingManager1 *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void org_bluez_leadvertising_manager1_call_register_advertisement (
    OrgBluezLEAdvertisingManager1 *proxy,
    const gchar *arg_advertisement,
    GVariant *arg_options,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_leadvertising_manager1_call_register_advertisement_finish (
    OrgBluezLEAdvertisingManager1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_leadvertising_manager1_call_register_advertisement_sync (
    OrgBluezLEAdvertisingManager1 *proxy,
    const gchar *arg_advertisement,
    GVariant *arg_options,
    GCancellable *cancellable,
    GError **error);

void org_bluez_leadvertising_manager1_call_unregister_advertisement (
    OrgBluezLEAdvertisingManager1 *proxy,
    const gchar *arg_object_path,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_leadvertising_manager1_call_unregister_advertisement_finish (
    OrgBluezLEAdvertisingManager1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_leadvertising_manager1_call_unregister_advertisement_sync (
    OrgBluezLEAdvertisingManager1 *proxy,
    const gchar *arg_object_path,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY (org_bluez_leadvertising_manager1_proxy_get_type ())
#define ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY, OrgBluezLEAdvertisingManager1Proxy))
#define ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY, OrgBluezLEAdvertisingManager1ProxyClass))
#define ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY, OrgBluezLEAdvertisingManager1ProxyClass))
#define IS_ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY))
#define IS_ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_PROXY))

typedef struct _OrgBluezLEAdvertisingManager1Proxy OrgBluezLEAdvertisingManager1Proxy;
typedef struct _OrgBluezLEAdvertisingManager1ProxyClass OrgBluezLEAdvertisingManager1ProxyClass;
typedef struct _OrgBluezLEAdvertisingManager1ProxyPrivate OrgBluezLEAdvertisingManager1ProxyPrivate;

struct _OrgBluezLEAdvertisingManager1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgBluezLEAdvertisingManager1ProxyPrivate *priv;
};

struct _OrgBluezLEAdvertisingManager1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_bluez_leadvertising_manager1_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgBluezLEAdvertisingManager1Proxy, g_object_unref)
#endif

void org_bluez_leadvertising_manager1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgBluezLEAdvertisingManager1 *org_bluez_leadvertising_manager1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgBluezLEAdvertisingManager1 *org_bluez_leadvertising_manager1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_bluez_leadvertising_manager1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgBluezLEAdvertisingManager1 *org_bluez_leadvertising_manager1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgBluezLEAdvertisingManager1 *org_bluez_leadvertising_manager1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON (org_bluez_leadvertising_manager1_skeleton_get_type ())
#define ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON, OrgBluezLEAdvertisingManager1Skeleton))
#define ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON, OrgBluezLEAdvertisingManager1SkeletonClass))
#define ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON, OrgBluezLEAdvertisingManager1SkeletonClass))
#define IS_ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON))
#define IS_ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_BLUEZ_LEADVERTISING_MANAGER1_SKELETON))

typedef struct _OrgBluezLEAdvertisingManager1Skeleton OrgBluezLEAdvertisingManager1Skeleton;
typedef struct _OrgBluezLEAdvertisingManager1SkeletonClass OrgBluezLEAdvertisingManager1SkeletonClass;
typedef struct _OrgBluezLEAdvertisingManager1SkeletonPrivate OrgBluezLEAdvertisingManager1SkeletonPrivate;

struct _OrgBluezLEAdvertisingManager1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgBluezLEAdvertisingManager1SkeletonPrivate *priv;
};

struct _OrgBluezLEAdvertisingManager1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_bluez_leadvertising_manager1_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgBluezLEAdvertisingManager1Skeleton, g_object_unref)
#endif

OrgBluezLEAdvertisingManager1 *org_bluez_leadvertising_manager1_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.bluez.LEAdvertisement1 */

#define TYPE_ORG_BLUEZ_LEADVERTISEMENT1 (org_bluez_leadvertisement1_get_type ())
#define ORG_BLUEZ_LEADVERTISEMENT1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1, OrgBluezLEAdvertisement1))
#define IS_ORG_BLUEZ_LEADVERTISEMENT1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1))
#define ORG_BLUEZ_LEADVERTISEMENT1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1, OrgBluezLEAdvertisement1Iface))

struct _OrgBluezLEAdvertisement1;
typedef struct _OrgBluezLEAdvertisement1 OrgBluezLEAdvertisement1;
typedef struct _OrgBluezLEAdvertisement1Iface OrgBluezLEAdvertisement1Iface;

struct _OrgBluezLEAdvertisement1Iface
{
  GTypeInterface parent_iface;

  gboolean (*handle_release) (
    OrgBluezLEAdvertisement1 *object,
    GDBusMethodInvocation *invocation);

};

GType org_bluez_leadvertisement1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_bluez_leadvertisement1_interface_info (void);
guint org_bluez_leadvertisement1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_bluez_leadvertisement1_complete_release (
    OrgBluezLEAdvertisement1 *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void org_bluez_leadvertisement1_call_release (
    OrgBluezLEAdvertisement1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_leadvertisement1_call_release_finish (
    OrgBluezLEAdvertisement1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_leadvertisement1_call_release_sync (
    OrgBluezLEAdvertisement1 *proxy,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_BLUEZ_LEADVERTISEMENT1_PROXY (org_bluez_leadvertisement1_proxy_get_type ())
#define ORG_BLUEZ_LEADVERTISEMENT1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_PROXY, OrgBluezLEAdvertisement1Proxy))
#define ORG_BLUEZ_LEADVERTISEMENT1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_PROXY, OrgBluezLEAdvertisement1ProxyClass))
#define ORG_BLUEZ_LEADVERTISEMENT1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_PROXY, OrgBluezLEAdvertisement1ProxyClass))
#define IS_ORG_BLUEZ_LEADVERTISEMENT1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_PROXY))
#define IS_ORG_BLUEZ_LEADVERTISEMENT1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_PROXY))

typedef struct _OrgBluezLEAdvertisement1Proxy OrgBluezLEAdvertisement1Proxy;
typedef struct _OrgBluezLEAdvertisement1ProxyClass OrgBluezLEAdvertisement1ProxyClass;
typedef struct _OrgBluezLEAdvertisement1ProxyPrivate OrgBluezLEAdvertisement1ProxyPrivate;

struct _OrgBluezLEAdvertisement1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgBluezLEAdvertisement1ProxyPrivate *priv;
};

struct _OrgBluezLEAdvertisement1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_bluez_leadvertisement1_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgBluezLEAdvertisement1Proxy, g_object_unref)
#endif

void org_bluez_leadvertisement1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgBluezLEAdvertisement1 *org_bluez_leadvertisement1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgBluezLEAdvertisement1 *org_bluez_leadvertisement1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_bluez_leadvertisement1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgBluezLEAdvertisement1 *org_bluez_leadvertisement1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgBluezLEAdvertisement1 *org_bluez_leadvertisement1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_BLUEZ_LEADVERTISEMENT1_SKELETON (org_bluez_leadvertisement1_skeleton_get_type ())
#define ORG_BLUEZ_LEADVERTISEMENT1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_SKELETON, OrgBluezLEAdvertisement1Skeleton))
#define ORG_BLUEZ_LEADVERTISEMENT1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_SKELETON, OrgBluezLEAdvertisement1SkeletonClass))
#define ORG_BLUEZ_LEADVERTISEMENT1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_SKELETON, OrgBluezLEAdvertisement1SkeletonClass))
#define IS_ORG_BLUEZ_LEADVERTISEMENT1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_SKELETON))
#define IS_ORG_BLUEZ_LEADVERTISEMENT1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_BLUEZ_LEADVERTISEMENT1_SKELETON))

typedef struct _OrgBluezLEAdvertisement1Skeleton OrgBluezLEAdvertisement1Skeleton;
typedef struct _OrgBluezLEAdvertisement1SkeletonClass OrgBluezLEAdvertisement1SkeletonClass;
typedef struct _OrgBluezLEAdvertisement1SkeletonPrivate OrgBluezLEAdvertisement1SkeletonPrivate;

struct _OrgBluezLEAdvertisement1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgBluezLEAdvertisement1SkeletonPrivate *priv;
};

struct _OrgBluezLEAdvertisement1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_bluez_leadvertisement1_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgBluezLEAdvertisement1Skeleton, g_object_unref)
#endif

OrgBluezLEAdvertisement1 *org_bluez_leadvertisement1_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.DBus.Properties */

#define TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES (org_freedesktop_dbus_properties_get_type ())
#define ORG_FREEDESKTOP_DBUS_PROPERTIES(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES, OrgFreedesktopDBusProperties))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES, OrgFreedesktopDBusPropertiesIface))

struct _OrgFreedesktopDBusProperties;
typedef struct _OrgFreedesktopDBusProperties OrgFreedesktopDBusProperties;
typedef struct _OrgFreedesktopDBusPropertiesIface OrgFreedesktopDBusPropertiesIface;

struct _OrgFreedesktopDBusPropertiesIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_get_all) (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_interface);

  gboolean (*handle_set) (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_interface,
    const gchar *arg_property,
    GVariant *arg_value);

};

GType org_freedesktop_dbus_properties_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_freedesktop_dbus_properties_interface_info (void);
guint org_freedesktop_dbus_properties_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_freedesktop_dbus_properties_complete_get_all (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation,
    GVariant *values);

void org_freedesktop_dbus_properties_complete_set (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void org_freedesktop_dbus_properties_call_get_all (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_properties_call_get_all_finish (
    OrgFreedesktopDBusProperties *proxy,
    GVariant **out_values,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_properties_call_get_all_sync (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface,
    GVariant **out_values,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_dbus_properties_call_set (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface,
    const gchar *arg_property,
    GVariant *arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_properties_call_set_finish (
    OrgFreedesktopDBusProperties *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_properties_call_set_sync (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface,
    const gchar *arg_property,
    GVariant *arg_value,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY (org_freedesktop_dbus_properties_proxy_get_type ())
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY, OrgFreedesktopDBusPropertiesProxy))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY, OrgFreedesktopDBusPropertiesProxyClass))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY, OrgFreedesktopDBusPropertiesProxyClass))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY))

typedef struct _OrgFreedesktopDBusPropertiesProxy OrgFreedesktopDBusPropertiesProxy;
typedef struct _OrgFreedesktopDBusPropertiesProxyClass OrgFreedesktopDBusPropertiesProxyClass;
typedef struct _OrgFreedesktopDBusPropertiesProxyPrivate OrgFreedesktopDBusPropertiesProxyPrivate;

struct _OrgFreedesktopDBusPropertiesProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgFreedesktopDBusPropertiesProxyPrivate *priv;
};

struct _OrgFreedesktopDBusPropertiesProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_freedesktop_dbus_properties_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusPropertiesProxy, g_object_unref)
#endif

void org_freedesktop_dbus_properties_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_freedesktop_dbus_properties_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON (org_freedesktop_dbus_properties_skeleton_get_type ())
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON, OrgFreedesktopDBusPropertiesSkeleton))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON, OrgFreedesktopDBusPropertiesSkeletonClass))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON, OrgFreedesktopDBusPropertiesSkeletonClass))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON))

typedef struct _OrgFreedesktopDBusPropertiesSkeleton OrgFreedesktopDBusPropertiesSkeleton;
typedef struct _OrgFreedesktopDBusPropertiesSkeletonClass OrgFreedesktopDBusPropertiesSkeletonClass;
typedef struct _OrgFreedesktopDBusPropertiesSkeletonPrivate OrgFreedesktopDBusPropertiesSkeletonPrivate;

struct _OrgFreedesktopDBusPropertiesSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgFreedesktopDBusPropertiesSkeletonPrivate *priv;
};

struct _OrgFreedesktopDBusPropertiesSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_freedesktop_dbus_properties_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusPropertiesSkeleton, g_object_unref)
#endif

OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_skeleton_new (void);


G_END_DECLS

#endif /* __ADVERTISE_GENERATED_H__ */
