/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __OBJECTMANAGER_GENERATED_H__
#define __OBJECTMANAGER_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.DBus.ObjectManager */

#define TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER (org_freedesktop_dbus_object_manager_get_type ())
#define ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER, OrgFreedesktopDBusObjectManager))
#define IS_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER))
#define ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER, OrgFreedesktopDBusObjectManagerIface))

struct _OrgFreedesktopDBusObjectManager;
typedef struct _OrgFreedesktopDBusObjectManager OrgFreedesktopDBusObjectManager;
typedef struct _OrgFreedesktopDBusObjectManagerIface OrgFreedesktopDBusObjectManagerIface;

struct _OrgFreedesktopDBusObjectManagerIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_managed_objects) (
    OrgFreedesktopDBusObjectManager *object,
    GDBusMethodInvocation *invocation);

  void (*interfaces_added) (
    OrgFreedesktopDBusObjectManager *object,
    const gchar *arg_object,
    GVariant *arg_interfaces);

  void (*interfaces_removed) (
    OrgFreedesktopDBusObjectManager *object,
    const gchar *arg_object,
    const gchar *const *arg_interfaces);

};

GType org_freedesktop_dbus_object_manager_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_freedesktop_dbus_object_manager_interface_info (void);
guint org_freedesktop_dbus_object_manager_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_freedesktop_dbus_object_manager_complete_get_managed_objects (
    OrgFreedesktopDBusObjectManager *object,
    GDBusMethodInvocation *invocation,
    GVariant *objects);



/* D-Bus signal emissions functions: */
void org_freedesktop_dbus_object_manager_emit_interfaces_added (
    OrgFreedesktopDBusObjectManager *object,
    const gchar *arg_object,
    GVariant *arg_interfaces);

void org_freedesktop_dbus_object_manager_emit_interfaces_removed (
    OrgFreedesktopDBusObjectManager *object,
    const gchar *arg_object,
    const gchar *const *arg_interfaces);



/* D-Bus method calls: */
void org_freedesktop_dbus_object_manager_call_get_managed_objects (
    OrgFreedesktopDBusObjectManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_object_manager_call_get_managed_objects_finish (
    OrgFreedesktopDBusObjectManager *proxy,
    GVariant **out_objects,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_object_manager_call_get_managed_objects_sync (
    OrgFreedesktopDBusObjectManager *proxy,
    GVariant **out_objects,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY (org_freedesktop_dbus_object_manager_proxy_get_type ())
#define ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY, OrgFreedesktopDBusObjectManagerProxy))
#define ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY, OrgFreedesktopDBusObjectManagerProxyClass))
#define ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY, OrgFreedesktopDBusObjectManagerProxyClass))
#define IS_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY))
#define IS_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_PROXY))

typedef struct _OrgFreedesktopDBusObjectManagerProxy OrgFreedesktopDBusObjectManagerProxy;
typedef struct _OrgFreedesktopDBusObjectManagerProxyClass OrgFreedesktopDBusObjectManagerProxyClass;
typedef struct _OrgFreedesktopDBusObjectManagerProxyPrivate OrgFreedesktopDBusObjectManagerProxyPrivate;

struct _OrgFreedesktopDBusObjectManagerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgFreedesktopDBusObjectManagerProxyPrivate *priv;
};

struct _OrgFreedesktopDBusObjectManagerProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_freedesktop_dbus_object_manager_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusObjectManagerProxy, g_object_unref)
#endif

void org_freedesktop_dbus_object_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusObjectManager *org_freedesktop_dbus_object_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusObjectManager *org_freedesktop_dbus_object_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_freedesktop_dbus_object_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusObjectManager *org_freedesktop_dbus_object_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusObjectManager *org_freedesktop_dbus_object_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON (org_freedesktop_dbus_object_manager_skeleton_get_type ())
#define ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON, OrgFreedesktopDBusObjectManagerSkeleton))
#define ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON, OrgFreedesktopDBusObjectManagerSkeletonClass))
#define ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON, OrgFreedesktopDBusObjectManagerSkeletonClass))
#define IS_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON))
#define IS_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_OBJECT_MANAGER_SKELETON))

typedef struct _OrgFreedesktopDBusObjectManagerSkeleton OrgFreedesktopDBusObjectManagerSkeleton;
typedef struct _OrgFreedesktopDBusObjectManagerSkeletonClass OrgFreedesktopDBusObjectManagerSkeletonClass;
typedef struct _OrgFreedesktopDBusObjectManagerSkeletonPrivate OrgFreedesktopDBusObjectManagerSkeletonPrivate;

struct _OrgFreedesktopDBusObjectManagerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgFreedesktopDBusObjectManagerSkeletonPrivate *priv;
};

struct _OrgFreedesktopDBusObjectManagerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_freedesktop_dbus_object_manager_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusObjectManagerSkeleton, g_object_unref)
#endif

OrgFreedesktopDBusObjectManager *org_freedesktop_dbus_object_manager_skeleton_new (void);


G_END_DECLS

#endif /* __OBJECTMANAGER_GENERATED_H__ */
